version: '3.9'
services:
  tempmail:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: tempmail
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./data/backend:/app/data
    ports:
      - "8080:8080"
      - "2525:2525"